database:
  host: "dpg-cdnhjnpa6gdooi6s6n50-a"
  port: 5432
  username: "dhairya"
  password: "fGcBChnpnKQXi8i5EudKVTJvG5iABFnr"
  database_name: "newsletter_8e23"
application:
  port: 8000
email_client:
  base_url: https://api.mailgun.net/v3/test.mailgun.org
  auth_token: test-835621cf-b09123a7
  sender: "test@newsletter.com"
  timeout_milliseconds: 10000

